//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    
    public enum ClassRole : int
    {
        Monitor = 0,
        StudyCommittee = 1,
        LifeCommittee = 2,
        LabourCommittee = 3,
        ArtCommittee = 4,
        SportCommittee = 5,
        Student = 6
    }
}
