//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    
    public enum ContactMethod : int
    {
        Text = 0,
        Phone = 1,
        Email = 2,
        WeChat = 3
    }
}
