//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent : Person
    {
        public int StudentId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string WeChat { get; set; }
        public ContactMethod Contact { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
