//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    
    public enum Priority : int
    {
        Extreme = 0,
        Important = 1,
        Suggested = 2,
        Dismissable = 3
    }
}
