//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    
    [Flags]
    public enum SchoolRule : int
    {
        Principal = 0,
        VicePrincipal = 1,
        Dean = 2,
        DeanOfDepartment = 3,
        DeanOfLevel = 4,
        Teacher = 5,
        DeanOfManagement = 6,
        Accountant = 7,
        Cashier = 8,
        Headmaster = 9
    }
}
