//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molecule.Data
{
    using System;
    
    public enum Subject : int
    {
        Chinese = 0,
        Mathematics = 1,
        English = 2,
        Science = 3,
        Moral = 4,
        PhysicalEducation = 5,
        Music = 6,
        Labour = 7,
        InformationTech = 8
    }
}
